# Copyright (c) 2018-2022 The MobileCoin Foundation
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "consensusNodeConfig.fullname" . }}-consensus-node
  labels:
    {{- include "consensusNodeConfig.labels" . | nindent 4 }}
data:
  CLIENT_HOSTNAME: {{ include "consensusNodeConfig.clientHostname" . | squote }}
  PEER_HOSTNAME: {{ include "consensusNodeConfig.peerHostname" . | squote }}
  BLOCK_VERSION: {{ .Values.global.node.nodeConfig.blockVersion | squote }}
  TX_SOURCE_URL: {{ include "consensusNodeConfig.txSourceUrl" . | squote }}
