[package]
name = "mc-util-cli"
version = "1.3.0-pre0"
authors = ["MobileCoin"]
edition = "2021"

[dependencies]
mc-util-build-info = { path = "../build/info" }

clap = { version = "3.1" }

[dev-dependencies]
clap = { version = "3.1", features = ['derive'] }
